//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL
    {
        public double CODCONTROL { get; set; }
        public string CODOPER { get; set; }
        public string NOMPRO { get; set; }
        public System.DateTime FECHCONTROL { get; set; }
        public string CONTROLTEXTO { get; set; }
    
        public virtual OPERADOR OPERADOR { get; set; }
    }
}
