//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int DTFCODIGOI { get; set; }
        public long FCTCODIGOI { get; set; }
        public string DTFDETALLE { get; set; }
        public Nullable<double> DTFCANTIDAD { get; set; }
        public Nullable<double> DTFVALOR { get; set; }
        public string DTFNOMBRE { get; set; }
        public Nullable<int> DTFGRABAIVA { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
    }
}
