//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_LIQUIDACION
    {
        public int DLQCODIGOI { get; set; }
        public int LQFCODIGOI { get; set; }
        public string DLQNOMBREP { get; set; }
        public System.DateTime DLQFECHAF { get; set; }
        public string DLQCIRUGIA { get; set; }
        public string DLQDETALLE { get; set; }
        public string DLQNUMFACTURA { get; set; }
        public double DLQVALOR { get; set; }
    
        public virtual LIQUIDACION_FACTURAS LIQUIDACION_FACTURAS { get; set; }
    }
}
