//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN_CIRUGIA
    {
        public long DTOCODIGOI { get; set; }
        public int ORCCODIGOI { get; set; }
        public int SRVCODIGOI { get; set; }
        public int TPCCODIGOI { get; set; }
        public string DTODETALLE { get; set; }
        public int DTOCANTID { get; set; }
        public double DTOVALOR { get; set; }
        public string DTOIDOJO { get; set; }
        public string DTONOMESP { get; set; }
    
        public virtual ORDEN_CIRUGIA ORDEN_CIRUGIA { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
        public virtual TIPO_CIRUGIA TIPO_CIRUGIA { get; set; }
    }
}
