//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA_CONVENIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA_CONVENIO()
        {
            this.ORDEN_CIRUGIA = new HashSet<ORDEN_CIRUGIA>();
            this.SERVICIO_EMPRESA_CONVENIO = new HashSet<SERVICIO_EMPRESA_CONVENIO>();
        }
    
        public int EMCCODIGOI { get; set; }
        public string EMCNOMBREC { get; set; }
        public string EMCNOMCOMERCIAL { get; set; }
        public string EMCRUC { get; set; }
        public string EMCDIRECC { get; set; }
        public string EMCTELEFOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_CIRUGIA> ORDEN_CIRUGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_EMPRESA_CONVENIO> SERVICIO_EMPRESA_CONVENIO { get; set; }
    }
}
