//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALISTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIALISTA()
        {
            this.LIQUIDACION_FACTURAS = new HashSet<LIQUIDACION_FACTURAS>();
            this.ORDEN_ESPECIALISTA = new HashSet<ORDEN_ESPECIALISTA>();
            this.PRESCRIPCIONES = new HashSet<PRESCRIPCIONES>();
        }
    
        public int ESPCODIGOI { get; set; }
        public string ESPCEDULAC { get; set; }
        public string ESPAPELLIDOP { get; set; }
        public string ESPAPELLIDOM { get; set; }
        public string ESPNOMBREC { get; set; }
        public System.DateTime ESPFECHAN { get; set; }
        public string ESPGENERO { get; set; }
        public string ESPDIRECCC { get; set; }
        public string ESPTELEFONOC { get; set; }
        public string ESPTELEFONCEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIQUIDACION_FACTURAS> LIQUIDACION_FACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_ESPECIALISTA> ORDEN_ESPECIALISTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESCRIPCIONES> PRESCRIPCIONES { get; set; }
    }
}
