//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_SIGNOS_VITALES
    {
        public int HSVCODIGOI { get; set; }
        public Nullable<int> SGVCODIGOI { get; set; }
        public Nullable<int> HSCCODIGOI { get; set; }
        public Nullable<System.DateTime> HSVFECHA { get; set; }
        public string HSVVALORES { get; set; }
    
        public virtual HISTORIA_CLINICA HISTORIA_CLINICA { get; set; }
        public virtual SIGNOS_VITALES SIGNOS_VITALES { get; set; }
    }
}
