//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPUESTOS()
        {
            this.FACTURA_RETENCION = new HashSet<FACTURA_RETENCION>();
        }
    
        public int IMPCODIGOI { get; set; }
        public string IMPDESCRIPCION { get; set; }
        public int IMPIDENTIFICACION { get; set; }
        public int IMPPORCENTAJE { get; set; }
        public bool IMPESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_RETENCION> FACTURA_RETENCION { get; set; }
    }
}
