//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDICES_CIE_SECUNDARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INDICES_CIE_SECUNDARIOS()
        {
            this.DIAGNOSTICOS = new HashSet<DIAGNOSTICOS>();
        }
    
        public int INSCODIGOI { get; set; }
        public Nullable<int> ICPCODIGOI { get; set; }
        public string INSDESCRIPCION { get; set; }
        public string INSIDCIE { get; set; }
        public Nullable<bool> INSESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAGNOSTICOS> DIAGNOSTICOS { get; set; }
        public virtual INDICES_CIE_PRINCIPALES INDICES_CIE_PRINCIPALES { get; set; }
    }
}
