//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMOS_MEDICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMOS_MEDICOS()
        {
            this.DETALLE_DESGLOSE_MEDICAMENTOS = new HashSet<DETALLE_DESGLOSE_MEDICAMENTOS>();
        }
    
        public int INMCODIGOI { get; set; }
        public Nullable<int> UNDCODIGOI { get; set; }
        public Nullable<int> PRVCODIGOI { get; set; }
        public string INMNOMBRE { get; set; }
        public Nullable<int> INMCANTIDAD { get; set; }
        public Nullable<decimal> INMVALORCOMPRA { get; set; }
        public Nullable<decimal> INMVALORVEMTA { get; set; }
        public Nullable<int> INMMINSTOCK { get; set; }
        public Nullable<bool> INMESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DESGLOSE_MEDICAMENTOS> DETALLE_DESGLOSE_MEDICAMENTOS { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual UNIDADES UNIDADES { get; set; }
    }
}
