//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIQUIDACION_FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIQUIDACION_FACTURAS()
        {
            this.DETALLE_LIQUIDACION = new HashSet<DETALLE_LIQUIDACION>();
        }
    
        public int LQFCODIGOI { get; set; }
        public int ESPCODIGOI { get; set; }
        public System.DateTime LQFFECHA { get; set; }
        public Nullable<bool> LQFESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_LIQUIDACION> DETALLE_LIQUIDACION { get; set; }
        public virtual ESPECIALISTA ESPECIALISTA { get; set; }
    }
}
