//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_ANTECEDENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTA_ANTECEDENTES()
        {
            this.HISTORIA_ANTECEDENTES = new HashSet<HISTORIA_ANTECEDENTES>();
        }
    
        public int LSACODIGOI { get; set; }
        public Nullable<int> TPACODIGOI { get; set; }
        public Nullable<decimal> LSACODCLINICO { get; set; }
        public string LSADESCRIPCION { get; set; }
        public Nullable<bool> LSAESTADO { get; set; }
    
        public virtual TIPOS_ANTECEDENTES TIPOS_ANTECEDENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIA_ANTECEDENTES> HISTORIA_ANTECEDENTES { get; set; }
    }
}
