//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPERADOR()
        {
            this.CONTROL = new HashSet<CONTROL>();
            this.ORDEN_CIRUGIA = new HashSet<ORDEN_CIRUGIA>();
            this.PROGRAMA = new HashSet<PROGRAMA>();
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public string CODOPER { get; set; }
        public int CODTIPO { get; set; }
        public string CEDULAC { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIC1 { get; set; }
        public string APELLIC2 { get; set; }
        public System.DateTime FECCREACION { get; set; }
        public System.DateTime FECCADUCID { get; set; }
        public string ESTADO { get; set; }
        public string CLAVE { get; set; }
        public int NUMOPERA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL> CONTROL { get; set; }
        public virtual TIPOS TIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_CIRUGIA> ORDEN_CIRUGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRAMA> PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
