//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_CIRUGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_CIRUGIA()
        {
            this.DESGLOSE_MEDICAMENTOS = new HashSet<DESGLOSE_MEDICAMENTOS>();
            this.DETALLE_ORDEN_CIRUGIA = new HashSet<DETALLE_ORDEN_CIRUGIA>();
            this.ORDEN_ESPECIALISTA = new HashSet<ORDEN_ESPECIALISTA>();
            this.FACTURA = new HashSet<FACTURA>();
            this.FACTURA1 = new HashSet<FACTURA>();
        }
    
        public int ORCCODIGOI { get; set; }
        public int PCTCODIGOI { get; set; }
        public int EMCCODIGOI { get; set; }
        public string CODOPER { get; set; }
        public System.DateTime ORCFECHA { get; set; }
        public string ORCOBSERVC { get; set; }
        public string ORCESTADOPAGO { get; set; }
        public string ORCESTADOCIR { get; set; }
        public Nullable<System.DateTime> ORCFECHAALTA { get; set; }
        public string ORCOBSERVGEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESGLOSE_MEDICAMENTOS> DESGLOSE_MEDICAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_CIRUGIA> DETALLE_ORDEN_CIRUGIA { get; set; }
        public virtual EMPRESA_CONVENIO EMPRESA_CONVENIO { get; set; }
        public virtual OPERADOR OPERADOR { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_ESPECIALISTA> ORDEN_ESPECIALISTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA1 { get; set; }
    }
}
