//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_ESPECIALISTA
    {
        public int ORCCODIGOI { get; set; }
        public int ESPCODIGOI { get; set; }
        public int TPECODIGOI { get; set; }
    
        public virtual ESPECIALISTA ESPECIALISTA { get; set; }
        public virtual ORDEN_CIRUGIA ORDEN_CIRUGIA { get; set; }
        public virtual TIPOESPECIALISTA TIPOESPECIALISTA { get; set; }
    }
}
