//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETROS
    {
        public int PRMCODIGOI { get; set; }
        public string PRMNOMEMP { get; set; }
        public Nullable<int> PRMIVA { get; set; }
        public string PRMIDLOCAL { get; set; }
        public string PRMNUMFACT { get; set; }
        public string PRMNUMCOMEG { get; set; }
        public string PRMNUMCOMRET { get; set; }
        public Nullable<bool> PRMESTADO { get; set; }
    }
}
