//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIE_FACTURA
    {
        public int PFCCODIGOI { get; set; }
        public long FCTCODIGOI { get; set; }
        public int FMPCODIGOI { get; set; }
        public int TRJCODIGOI { get; set; }
        public double PFCSUBTOTAL { get; set; }
        public double PFCIVA { get; set; }
        public double PFCTOTAL { get; set; }
        public Nullable<double> PCFRECARGO { get; set; }
        public string PCFNOMTARJETA { get; set; }
        public string PCFNUMTARJETA { get; set; }
        public string PCFNUMLOTE { get; set; }
        public string PCFNUMTRANS { get; set; }
        public Nullable<int> CNBCODIGOI { get; set; }
    
        public virtual CUENTA_BANCO CUENTA_BANCO { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual TARJETA_CREDITO TARJETA_CREDITO { get; set; }
        public virtual FACTURA FACTURA { get; set; }
    }
}
