//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIE_DESGLOSE
    {
        public int PDSCODIGOI { get; set; }
        public Nullable<int> SRVCODIGOI { get; set; }
        public Nullable<int> DSMCODIGOI { get; set; }
        public Nullable<decimal> PDSSUBTOTAL { get; set; }
        public Nullable<decimal> PDSVALORSERVICIO { get; set; }
        public Nullable<decimal> PDSTOTAL { get; set; }
    
        public virtual DESGLOSE_MEDICAMENTOS DESGLOSE_MEDICAMENTOS { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
