//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROGRAMA()
        {
            this.OPERADOR = new HashSet<OPERADOR>();
        }
    
        public int CODPROG { get; set; }
        public Nullable<short> CODMENUS { get; set; }
        public string NOMPROG { get; set; }
        public string DESCPROG { get; set; }
        public Nullable<short> PTIPO { get; set; }
        public Nullable<short> NIVEL { get; set; }
        public string VARPROG { get; set; }
    
        public virtual MENUS MENUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPERADOR> OPERADOR { get; set; }
    }
}
