//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIOS()
        {
            this.DETALLE_ORDEN_CIRUGIA = new HashSet<DETALLE_ORDEN_CIRUGIA>();
            this.PIE_DESGLOSE = new HashSet<PIE_DESGLOSE>();
            this.SERVICIO_EMPRESA_CONVENIO = new HashSet<SERVICIO_EMPRESA_CONVENIO>();
        }
    
        public int SRVCODIGOI { get; set; }
        public string SRVDESCRIPC { get; set; }
        public double SRVVALOR { get; set; }
        public string SRVIDINGRESO { get; set; }
        public string SRVREQUIERENOM { get; set; }
        public Nullable<int> SRVCODIGOESP { get; set; }
        public string SRVIDENTIFIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_CIRUGIA> DETALLE_ORDEN_CIRUGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIE_DESGLOSE> PIE_DESGLOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_EMPRESA_CONVENIO> SERVICIO_EMPRESA_CONVENIO { get; set; }
    }
}
