//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_EMPRESA_CONVENIO
    {
        public int SECCODIGOI { get; set; }
        public int EMCCODIGOI { get; set; }
        public int TPCCODIGOI { get; set; }
        public int SRVCODIGOI { get; set; }
        public string SECIDCOD { get; set; }
        public double SECVALOR { get; set; }
    
        public virtual EMPRESA_CONVENIO EMPRESA_CONVENIO { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
