//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRIRetencionCompraDetalle
    {
        public int idDetalleRetencion { get; set; }
        public Nullable<int> idRetencion { get; set; }
        public string codigoretiva { get; set; }
        public Nullable<decimal> baseretiva { get; set; }
        public Nullable<decimal> porcretiva { get; set; }
        public Nullable<decimal> valorretiva { get; set; }
        public string codigoretrenta { get; set; }
        public Nullable<decimal> baseretrenta { get; set; }
        public Nullable<decimal> porcretrenta { get; set; }
        public Nullable<decimal> valorretrenta { get; set; }
    }
}
