//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRIRetencionCompraEncab
    {
        public int idRetencion { get; set; }
        public string secuencial { get; set; }
        public Nullable<System.DateTime> fechaemision { get; set; }
        public Nullable<int> idsujetoretencion { get; set; }
        public string coddocsustentoret { get; set; }
        public string numdocsustento { get; set; }
        public Nullable<System.DateTime> fechaemidocsustento { get; set; }
        public Nullable<int> escompra { get; set; }
        public Nullable<int> idfactura { get; set; }
    }
}
