//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_ORDENES
    {
        public int ORCCODIGOI { get; set; }
        public System.DateTime ORCFECHA { get; set; }
        public string PCTCEDULAC { get; set; }
        public string nombre { get; set; }
        public string TPCDESCRIPC { get; set; }
        public double DTOVALOR { get; set; }
        public string DTOIDOJO { get; set; }
        public string nomesp { get; set; }
        public string TPEDESCRIPC { get; set; }
        public string EMCNOMbrec { get; set; }
        public string ORCESTADOPAGO { get; set; }
    }
}
