//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_EXAMENES_FISICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPOS_EXAMENES_FISICOS()
        {
            this.EXAMENES_FISICOS = new HashSet<EXAMENES_FISICOS>();
        }
    
        public int TPFCODIGOI { get; set; }
        public string TPFDESCRIPCION { get; set; }
        public bool TPFESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMENES_FISICOS> EXAMENES_FISICOS { get; set; }
    }
}
