//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_ANTECEDENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPOS_ANTECEDENTES()
        {
            this.LISTA_ANTECEDENTES = new HashSet<LISTA_ANTECEDENTES>();
        }
    
        public int TPACODIGOI { get; set; }
        public string TPADESCRIPCION { get; set; }
        public string TPASIGLAS { get; set; }
        public Nullable<bool> TPAESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_ANTECEDENTES> LISTA_ANTECEDENTES { get; set; }
    }
}
