//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CIRUGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_CIRUGIA()
        {
            this.DETALLE_ORDEN_CIRUGIA = new HashSet<DETALLE_ORDEN_CIRUGIA>();
        }
    
        public int TPCCODIGOI { get; set; }
        public double TPCVALOR { get; set; }
        public string TPCDESCRIPC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_CIRUGIA> DETALLE_ORDEN_CIRUGIA { get; set; }
    }
}
